
-- Create User Roles Enum
CREATE TYPE user_role AS ENUM ('admin', 'student');

-- Profiles Table
-- Stores user information and links to Supabase Auth.
CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    email VARCHAR(255) UNIQUE NOT NULL,
    role user_role NOT NULL DEFAULT 'student',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- PDF Uploads Table
-- Tracks uploaded PDF files and their parsing status.
CREATE TYPE parsing_status AS ENUM ('pending', 'processing', 'completed', 'failed');

CREATE TABLE pdf_uploads (
    id SERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    storage_path VARCHAR(1024) NOT NULL,
    status parsing_status NOT NULL DEFAULT 'pending',
    uploaded_by UUID REFERENCES profiles(id),
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Questions Table
-- Stores individual multiple-choice questions extracted from PDFs.
CREATE TABLE questions (
    id SERIAL PRIMARY KEY,
    source_pdf_id INTEGER REFERENCES pdf_uploads(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    explanation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Question Options Table
-- Stores the answer options for each question.
CREATE TABLE question_options (
    id SERIAL PRIMARY KEY,
    question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
    option_text TEXT NOT NULL,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE
);

-- Exams Table
-- Defines a specific exam instance generated by an Admin.
CREATE TABLE exams (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    created_by UUID REFERENCES profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Exam Questions Table (Join Table)
-- Links an exam to its set of randomly ordered questions.
CREATE TABLE exam_questions (
    id SERIAL PRIMARY KEY,
    exam_id INTEGER REFERENCES exams(id) ON DELETE CASCADE,
    question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
    display_order INTEGER NOT NULL -- Stores the shuffled order for this specific exam
);

-- Attempts Table
-- Tracks a student's attempt to take an exam.
CREATE TABLE attempts (
    id SERIAL PRIMARY KEY,
    exam_id INTEGER REFERENCES exams(id) ON DELETE CASCADE,
    student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_time TIMESTAMPTZ,
    score INTEGER,
    is_submitted BOOLEAN NOT NULL DEFAULT FALSE
);

-- Attempt Answers Table
-- Stores the student's selected answer for each question in an attempt.
-- This is the core of the auto-save functionality.
CREATE TABLE attempt_answers (
    id SERIAL PRIMARY KEY,
    attempt_id INTEGER REFERENCES attempts(id) ON DELETE CASCADE,
    question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
    selected_option_id INTEGER REFERENCES question_options(id),
    is_correct BOOLEAN,
    saved_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Parsing Faults Table
-- Logs any errors or irregularities found during the PDF parsing process.
CREATE TABLE parsing_faults (
    id SERIAL PRIMARY KEY,
    pdf_upload_id INTEGER REFERENCES pdf_uploads(id),
    description TEXT NOT NULL,
    raw_text TEXT, -- The problematic text from the PDF
    suggested_fix TEXT,
    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    reported_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security for all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE pdf_uploads ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE question_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE attempt_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE parsing_faults ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Profiles
CREATE POLICY "Users can view their own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admins can view all profiles" ON profiles
    FOR SELECT USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- RLS Policies for PDF Uploads
CREATE POLICY "Admins can manage PDF uploads" ON pdf_uploads
    FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- RLS Policies for Questions & Options (assuming they are public once created)
CREATE POLICY "All users can view questions and options" ON questions
    FOR SELECT USING (true);
CREATE POLICY "All users can view question options" ON question_options
    FOR SELECT USING (true);
CREATE POLICY "Admins can manage questions and options" ON questions
    FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can manage question options" ON question_options
    FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- RLS Policies for Exams
CREATE POLICY "All users can view exams" ON exams
    FOR SELECT USING (true);
CREATE POLICY "Admins can manage exams" ON exams
    FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Admins can manage exam questions" ON exam_questions
    FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));


-- RLS Policies for Attempts
CREATE POLICY "Students can view and manage their own attempts" ON attempts
    FOR ALL USING (auth.uid() = student_id);
CREATE POLICY "Admins can view all attempts" ON attempts
    FOR SELECT USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- RLS Policies for Attempt Answers
CREATE POLICY "Students can view and manage their own attempt answers" ON attempt_answers
    FOR ALL USING (EXISTS (SELECT 1 FROM attempts WHERE id = attempt_id AND student_id = auth.uid()));
CREATE POLICY "Admins can view all attempt answers" ON attempt_answers
    FOR SELECT USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- RLS Policies for Parsing Faults
CREATE POLICY "Admins can manage parsing faults" ON parsing_faults
    FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
